### ISSUE TITLE
Backend & Frontend Routes

### ISSUE THREAD

**Issue by paulobocanegra** [safetyboi/FullStack_Project#4]
# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain superfluous routes
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

**Comment by paulobocanegra** [comment]
Backend:

I would highly recommend you to have a table and a route for `cart_items`. We will need index, create, update, and destroy to do shopping cart logic

**Comment by safetyboi** [comment]
Will it suffice to have one CartItems component that will house all the buttons for create/update/destroy behavior?

Other than that, I think I'm good.

**Comment by paulobocanegra** [comment]
It will definitely suffice. You just need the CartItemIndex and we can have all the buttons that trigger those actions on each CartIndexItem component.

Excellent work updating the Backend routes!

**Comment by paulobocanegra** [comment]
Frontend routes:

- /cart_items
   - CartItems
   
The CartItems component should be rendered at `"/"` if you plan to always have the shopping cart on the top right of the page. If you only want to see the shopping cart at a different frontend route that is a different story. I do think that it might be cool to have a checkout page. A frontend route for `/checkout` where the user can fill up a form and we can simulate the purchase.

**Comment by paulobocanegra** [comment]
Excellent work! 💯
